package projeto_1;

import java.awt.FlowLayout;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import projeto_1.controller.cliente.ClienteController;
import projeto_1.controller.funcionario.FuncionarioController;
import projeto_1.controller.produto.ProdutoController;
import projeto_1.view.cadastro.TelaCadastro;

public class TelaPrincipal extends JFrame {
    
public TelaPrincipal() {
    super("Exemplo JFrame e JDialog");
    initComponents();
    configurarJanela();
}


private void configurarJanela() {
    setTitle("Sistema Comercial");
    setSize(500, 350);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setResizable(false);
    setAlwaysOnTop(true);
    setLayout(new FlowLayout());
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroClientes = new javax.swing.JMenuItem();
        jMenuItemCadastroProdutos = new javax.swing.JMenuItem();
        jMenuItemCadastroFuncionarios = new javax.swing.JMenuItem();
        jMenuMovimentacoes = new javax.swing.JMenu();
        jMenuItemMovimentacoesVendas = new javax.swing.JMenuItem();
        jMenuItemMovimentacoesCompras = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemSistemaEstoque = new javax.swing.JMenuItem();
        jMenuItemSistemaFinanceiro = new javax.swing.JMenuItem();
        JMenuSistema = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroClientes.setText("Clientes");
        jMenuItemCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroClientes);

        jMenuItemCadastroProdutos.setText("Produtos");
        jMenuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProdutos);

        jMenuItemCadastroFuncionarios.setText("Funcionários");
        jMenuItemCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroFuncionarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuMovimentacoes.setText("Movimentações");

        jMenuItemMovimentacoesVendas.setText("Vendas");
        jMenuMovimentacoes.add(jMenuItemMovimentacoesVendas);

        jMenuItemMovimentacoesCompras.setText("Compras");
        jMenuMovimentacoes.add(jMenuItemMovimentacoesCompras);

        jMenuBar1.add(jMenuMovimentacoes);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemSistemaEstoque.setText("Estoque");
        jMenuRelatorios.add(jMenuItemSistemaEstoque);

        jMenuItemSistemaFinanceiro.setText("Financeiro");
        jMenuItemSistemaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSistemaFinanceiroActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemSistemaFinanceiro);

        jMenuBar1.add(jMenuRelatorios);

        JMenuSistema.setText("Sistema");

        jMenuItem13.setText("Configurações");
        JMenuSistema.add(jMenuItem13);

        jMenuItem14.setText("Sair");
        JMenuSistema.add(jMenuItem14);

        jMenuBar1.add(JMenuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSistemaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSistemaFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSistemaFinanceiroActionPerformed

    private void jMenuItemCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroClientesActionPerformed
        
        TelaCadastro telaCadastro = new TelaCadastro(this, new ClienteController());
        
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroClientesActionPerformed

    private void jMenuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutosActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro(this, new ProdutoController());
        
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutosActionPerformed

    private void jMenuItemCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroFuncionariosActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro(this, new FuncionarioController());
        
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroFuncionariosActionPerformed

    
    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuSistema;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCadastroClientes;
    private javax.swing.JMenuItem jMenuItemCadastroFuncionarios;
    private javax.swing.JMenuItem jMenuItemCadastroProdutos;
    private javax.swing.JMenuItem jMenuItemMovimentacoesCompras;
    private javax.swing.JMenuItem jMenuItemMovimentacoesVendas;
    private javax.swing.JMenuItem jMenuItemSistemaEstoque;
    private javax.swing.JMenuItem jMenuItemSistemaFinanceiro;
    private javax.swing.JMenu jMenuMovimentacoes;
    private javax.swing.JMenu jMenuRelatorios;
    // End of variables declaration//GEN-END:variables

}